services:
  sisaxs_web:
    build: ./
    command: /app/docker-entrypoint.sh
    ports:
      - 51080:80
      - 51006:3306
    volumes:
      - ./:/var/www/html
      - my_db:/var/lib/mysql

volumes:
  my_db:
